name: ammonite
description: "A new Flutter project."
publish_to: "none"
version: 0.2.4+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  system_theme: ^2.3.1
  video_player: ^2.8.3
  webview_flutter: ^4.7.0
  chewie: ^1.8.1
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^10.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/ic_launcher.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
